// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqxmmonqibpmnxgypevd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxeG1tb25xaWJwbW54Z3lwZXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzY5NjgsImV4cCI6MjA2NjQ1Mjk2OH0.YD4lgNYy1m6B0EjKZEPePKSXRyOXu95i3SC3tJdIZmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});