project_id = "xjknkjbrjgljuovaazeu"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-diagnostic-checkout-session]
verify_jwt = true

[functions.create-advisory-checkout-session]
verify_jwt = true

[functions.send-password-reset-otp]
verify_jwt = false

[functions.verify-password-reset-otp]
verify_jwt = false
