//go:build e2e

// Package e2e — shared fixture helpers for both Linux and Windows E2E tests.
package e2e

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// ─────────────────────────────────────────────────────────────────────────────
// SSP fixture
// ─────────────────────────────────────────────────────────────────────────────

// writeMinimalSSP writes a minimal SSP JSON file that adinkhepra ssp export can read.
func writeMinimalSSP(t *testing.T, path, systemName string) {
	t.Helper()
	ssp := map[string]interface{}{
		"system_name":        systemName,
		"responsible_org":    "NouchiX / SecRed Knowledge Inc.",
		"isso":               "ISSM",
		"impact_level":       "Moderate",
		"cui_categories":     []string{"Controlled Technical Information (CTI)"},
		"system_description": "E2E test SSP generated by Phantom Sandbox",
		"system_environment": "Linux Alpine (DummyTarget)",
		"components_in_boundary": []string{"e2e-target"},
		"controls":           []map[string]interface{}{},
	}
	data, _ := json.MarshalIndent(ssp, "", "  ")
	if err := os.WriteFile(path, data, 0644); err != nil {
		t.Fatalf("writeMinimalSSP: %v", err)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Scan results fixture
// ─────────────────────────────────────────────────────────────────────────────

// writeMinimalScanResults writes a minimal scan results JSON for POAM generation.
func writeMinimalScanResults(t *testing.T, path string) {
	t.Helper()
	results := map[string]interface{}{
		"scan_id":    "e2e-test-001",
		"target":     "127.0.0.1",
		"scanned_at": time.Now().UTC().Format(time.RFC3339),
		"risk_score": 45,
		"open_ports": []int{22, 80, 8080},
		"findings": []map[string]interface{}{
			{
				"id":          "V-220700",
				"title":       "SSH PermitRootLogin must be disabled",
				"severity":    "HIGH",
				"status":      "OPEN",
				"control":     "AC-2",
				"description": "SSH root login is enabled — violates STIG V-220700",
				"remediation": "Set PermitRootLogin no in /etc/ssh/sshd_config",
				"cost":        50000.0,
			},
			{
				"id":          "SC-8-HTTP",
				"title":       "HTTP without TLS on port 80",
				"severity":    "HIGH",
				"status":      "OPEN",
				"control":     "SC-8",
				"description": "Plaintext HTTP exposed — violates NIST 800-171 3.13.8",
				"remediation": "Redirect all HTTP to HTTPS",
				"cost":        25000.0,
			},
			{
				"id":          "PQC-001",
				"title":       "Legacy 3DES cipher in SSH config",
				"severity":    "CRITICAL",
				"status":      "OPEN",
				"control":     "SC-13",
				"description": "3DES-CBC is quantum-vulnerable — CNSA 2.0 non-compliant",
				"remediation": "Remove 3DES from Ciphers in sshd_config",
				"cost":        100000.0,
			},
		},
	}
	data, _ := json.MarshalIndent(results, "", "  ")
	if err := os.WriteFile(path, data, 0644); err != nil {
		t.Fatalf("writeMinimalScanResults: %v", err)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// File helpers
// ─────────────────────────────────────────────────────────────────────────────

// fileSize returns the size of the file at path in bytes.
func fileSize(t *testing.T, path string) int64 {
	t.Helper()
	info, err := os.Stat(path)
	if err != nil {
		return 0
	}
	return info.Size()
}

// keys returns the keys of a map[string]interface{}.
func keys(m map[string]interface{}) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	return ks
}

// ─────────────────────────────────────────────────────────────────────────────
// Ensure filepath imported (used by fileSize path base in assertions)
// ─────────────────────────────────────────────────────────────────────────────

var _ = filepath.Base

// ─────────────────────────────────────────────────────────────────────────────
// Directory search helpers (used by both Linux and Windows E2E tests)
// ─────────────────────────────────────────────────────────────────────────────

// findPDFInDir scans dir for a .pdf file whose name contains prefix.
func findPDFInDir(t *testing.T, dir, prefix string) string {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return ""
	}
	prefix = strings.ToLower(prefix)
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := strings.ToLower(e.Name())
		if strings.HasSuffix(name, ".pdf") && strings.Contains(name, prefix) {
			return filepath.Join(dir, e.Name())
		}
	}
	return ""
}

// findAnyOutputInDir scans dir for any file whose name contains prefix.
func findAnyOutputInDir(t *testing.T, dir, prefix string) string {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return ""
	}
	prefix = strings.ToLower(prefix)
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if strings.Contains(strings.ToLower(e.Name()), prefix) {
			return filepath.Join(dir, e.Name())
		}
	}
	return ""
}

// findOutputFile finds a CLI output file in dir that contains prefix,
// excluding files with any of the given extensions (e.g. ".json" for inputs).
// Priority order: .pdf, then .md, then any other match.
func findOutputFile(t *testing.T, dir, prefix string, excludeExts ...string) string {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return ""
	}
	prefix = strings.ToLower(prefix)

	var pdfMatch, mdMatch, anyMatch string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := strings.ToLower(e.Name())
		if !strings.Contains(name, prefix) {
			continue
		}
		excluded := false
		for _, ext := range excludeExts {
			if strings.HasSuffix(name, strings.ToLower(ext)) {
				excluded = true
				break
			}
		}
		if excluded {
			continue
		}
		full := filepath.Join(dir, e.Name())
		switch {
		case strings.HasSuffix(name, ".pdf") && pdfMatch == "":
			pdfMatch = full
		case strings.HasSuffix(name, ".md") && mdMatch == "":
			mdMatch = full
		case anyMatch == "":
			anyMatch = full
		}
	}
	if pdfMatch != "" {
		return pdfMatch
	}
	if mdMatch != "" {
		return mdMatch
	}
	return anyMatch
}
