// pkg/asaf/daemon/staging_backends.go — Staging Isolation Backends
//
// Implements the StagingBackend interface with two backends, selected
// automatically by SelectBackend():
//
//   DockerBackend  — primary. Runs a single container using the profile-specific
//                    mirror image. No --read-only: Docker overlay provides COW
//                    isolation; changes are discarded when the container exits.
//                    stage.sh (embedded below) captures before/after file state
//                    around the command, emitting structured ASAF_* markers.
//
//   DryRunBackend  — fallback. No execution. Reads the current state of affected
//                    files on the HOST filesystem and reports them as "before"
//                    state, with "after" identical (command not run). Use when
//                    Docker is unavailable or for Windows endpoints where no
//                    container image exists yet.
//
// The NamespaceBackend (Linux kernel overlayfs, no Docker required) is a
// planned third option and is not yet implemented.

package daemon

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
)

// stageScript is the shell script written to a tmpfile and mounted read-only
// into the staging container at /asaf/stage.sh.
//
// Protocol:
//   Arguments: file1 [file2 ...] -- cmd [arg1 arg2 ...]
//   Stdout:    ASAF_BEFORE_BEGIN/END, ASAF_AFTER_BEGIN/END, ASAF_EXIT_CODE
//              markers interleaved with any command stdout.
//   Parsed by: parseStageOutput() in staging.go.
//
// Portability: POSIX sh only — no bashisms. "$@" executes the command directly
// after the -- separator so no shell word-splitting applies to command args.
// The container has --cap-drop ALL --network none, so the sh-layer attack
// surface is already bounded.
const stageScript = `#!/bin/sh
# ASAF single-container staging script — generated by asaf-daemon, NOT hand-edited.
# See staging_backends.go (stageScript) for the authoritative copy.

# Parse args: files... -- cmd args...
_files=""
while [ $# -gt 0 ] && [ "$1" != "--" ]; do
    _files="$_files $1"
    shift
done
[ $# -gt 0 ] && shift  # consume --

# Capture before state
for _f in $_files; do
    printf 'ASAF_BEFORE_BEGIN %s\n' "$_f"
    cat "$_f" 2>/dev/null || true
    printf 'ASAF_BEFORE_END %s\n' "$_f"
done

# Execute the staged command; capture its exit code.
"$@"
_asaf_exit=$?

# Capture after state
for _f in $_files; do
    printf 'ASAF_AFTER_BEGIN %s\n' "$_f"
    cat "$_f" 2>/dev/null || true
    printf 'ASAF_AFTER_END %s\n' "$_f"
done

printf 'ASAF_EXIT_CODE %d\n' "$_asaf_exit"
exit "$_asaf_exit"
`

// mirrorImages maps STIGProfile values to container image references.
// An empty string means no image is available for that profile; SelectBackend
// will fall through to DryRunBackend.
var mirrorImages = map[string]string{
	"rhel9":   "ghcr.io/nouchix/asaf-mirror-rhel9:latest",
	"rhel10":  "ghcr.io/nouchix/asaf-mirror-rhel10:latest",
	"ubuntu":  "ghcr.io/nouchix/asaf-mirror-ubuntu-2204:latest",
	"windows": "", // no Windows container image yet — falls through to dry-run
}

// mirrorImageForProfile returns the container image for a given STIGProfile.
// Defaults to rhel9 when profile is empty. Checks ASAF_MIRROR_IMAGE env override.
func mirrorImageForProfile(profile string) string {
	if override := mirrorImage(); override != mirrorImages["rhel9"] {
		// operator has set ASAF_MIRROR_IMAGE — honour it unconditionally
		return override
	}
	if profile == "" {
		profile = "rhel9"
	}
	return mirrorImages[profile] // empty string = no image for this profile
}

// StagingBackend is the interface for staging isolation mechanisms.
type StagingBackend interface {
	// Available reports whether this backend can run on the current host.
	Available() bool
	// Run executes req in isolation and returns a StagingResult.
	// The Attestation field is NOT populated by Run — that is done by
	// StagingManager.runJob after backend.Run returns.
	Run(ctx context.Context, req *ChangeRequest) (*StagingResult, error)
}

// SelectBackend returns the best available backend for the given STIGProfile.
//
//	DockerBackend  — if Docker is available and a mirror image exists for profile
//	DryRunBackend  — fallback (always available)
func SelectBackend(profile string) StagingBackend {
	img := mirrorImageForProfile(profile)
	if img != "" {
		d := &DockerBackend{mirrorImage: img}
		if d.Available() {
			return d
		}
	}
	return &DryRunBackend{}
}

// ─── DockerBackend ────────────────────────────────────────────────────────────

// DockerBackend runs the staged command in a single ephemeral container using
// the profile-appropriate mirror image. Docker's overlay layer provides
// copy-on-write isolation; the container is removed on exit (--rm) so no
// changes persist to the host.
type DockerBackend struct {
	mirrorImage string
}

// Available returns true if Docker is reachable and the backend has a mirror image.
func (b *DockerBackend) Available() bool {
	if b.mirrorImage == "" {
		return false
	}
	return dockerAvailable()
}

// Run writes stage.sh to a tmpfile, mounts it into a single container, and
// parses the structured ASAF_* output into a StagingResult.
func (b *DockerBackend) Run(ctx context.Context, req *ChangeRequest) (*StagingResult, error) {
	// Write stage.sh to a temp file so it can be mounted read-only into the container.
	scriptFile, err := os.CreateTemp("", "asaf-stage-*.sh")
	if err != nil {
		return nil, fmt.Errorf("docker backend: create stage.sh temp file: %w", err)
	}
	defer os.Remove(scriptFile.Name())
	if _, err := scriptFile.WriteString(stageScript); err != nil {
		scriptFile.Close()
		return nil, fmt.Errorf("docker backend: write stage.sh: %w", err)
	}
	if err := scriptFile.Close(); err != nil {
		return nil, fmt.Errorf("docker backend: close stage.sh: %w", err)
	}

	affectedFiles := affectedFilesByCommand(req.Command)

	// Single-container staging:
	//   - No --read-only: Docker overlay gives the container a writable layer
	//     discarded on --rm. Commands that write to /etc (faillock, authselect,
	//     sysctl) now succeed. See package doc for the --read-only / --tmpfs /etc
	//     misconception that the old code fell into.
	//   - stage.sh is mounted read-only so the staged command cannot tamper
	//     with the snapshot/reporting logic.
	//   - /tmp and /run are tmpfs so commands that need temp space still work.
	jobName := "asaf-mirror-" + req.ControlID[:min(8, len(req.ControlID))]
	dockerArgs := []string{
		"run", "--rm",
		"--name", jobName,
		"--tmpfs", "/tmp",
		"--tmpfs", "/run",
		"--security-opt", "no-new-privileges",
		"--cap-drop", "ALL",
		"--network", "none",
		"--volume", scriptFile.Name() + ":/asaf/stage.sh:ro",
		b.mirrorImage,
		"/bin/sh", "/asaf/stage.sh",
	}
	dockerArgs = append(dockerArgs, affectedFiles...)
	dockerArgs = append(dockerArgs, "--")
	dockerArgs = append(dockerArgs, req.Command...)

	//nolint:gosec — command validated by validateCommand() before staging
	cmd := exec.CommandContext(ctx, "docker", dockerArgs...)
	var buf bytes.Buffer
	cmd.Stdout = &buf
	cmd.Stderr = &buf

	_ = cmd.Run() // exit code comes from ASAF_EXIT_CODE marker, not from docker

	rawOutput := buf.String()
	diffs, exitCode := parseStageOutput(rawOutput)

	stdout := filterASAFMarkers(rawOutput)
	stdout = truncateOutput(stdout, 32*1024)

	return &StagingResult{
		Diffs:       diffs,
		Stdout:      stdout,
		ExitCode:    exitCode,
		BackendType: "docker",
	}, nil
}

// ─── DryRunBackend ────────────────────────────────────────────────────────────

// DryRunBackend performs read-only analysis without executing the command.
// It captures the current state of affected files on the host and reports
// them as "before" state, with "after" identical (command not run).
//
// Appropriate for:
//   - Endpoints where Docker is not installed
//   - Windows endpoints (no container image yet)
//   - Belt-and-suspenders operators who want zero execution during staging
//   - Initial ASAF deployment (conservative mode before trust is established)
type DryRunBackend struct{}

// Available always returns true — dry-run has no external dependencies.
func (b *DryRunBackend) Available() bool { return true }

// Run captures host filesystem state for affected files and returns a result
// showing what the command WOULD affect, without executing it.
func (b *DryRunBackend) Run(_ context.Context, req *ChangeRequest) (*StagingResult, error) {
	files := affectedFilesByCommand(req.Command)
	state := captureFileContents(files)
	diffs := buildDryRunDiffs(files, state)

	notice := fmt.Sprintf(
		"[dry-run] command NOT executed: %v\nCurrent state of %d affected file(s) captured from host.",
		req.Command, len(files),
	)
	return &StagingResult{
		Diffs:       diffs,
		Stdout:      notice,
		ExitCode:    0,
		BackendType: "dry-run",
	}, nil
}

// min is a local helper for Go versions before 1.21's built-in min.
func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
