// Code generated by stig-updater --gen-go on 2026-07-02T00:15:09Z.
// Source: DISA RHEL_9 XCCDF benchmark — 0 rules.
// DO NOT EDIT MANUALLY. Re-generate with:
//   go run ./cmd/stig-updater --mode online --filter RHEL_9 --gen-go
package stig

// rhel09STIG contains all CheckSpec rows derived from the DISA RHEL_9
// XCCDF benchmark.  Each row's metadata (Title, Severity, CCI refs) is resolved
// at runtime from the embedded STIG_CCI_Map.csv — it is not duplicated here.
var rhel09STIG = []CheckSpec{
}
