package stig

import "fmt"

// validateTableSTIG is the generic table-driven validator for all OS families
// whose check tables are generated by cmd/stig-updater --gen-all.
// It replaces per-OS hand-written check functions.
func (v *Validator) validateTableSTIG(result *ValidationResult, version string, table []CheckSpec) error {
	result.Version = version

	checker := NewSystemChecker()
	db, err := GetDatabase()
	if err != nil {
		return fmt.Errorf("load compliance database: %w", err)
	}

	for _, spec := range table {
		result.Findings = append(result.Findings, RunCheck(spec, checker, db))
	}
	return nil
}
