package audit

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/dag"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/shodan"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/stigs"
)

// RiskReport is the output generated by Khepra after analyzing a Sonar Snapshot.
type RiskReport struct {
	Client   string      `json:"client"`
	ScanID   string      `json:"scan_id"`
	Risks    []RiskItem  `json:"risks"`
	TrustMap *dag.Memory `json:"trust_map_snapshot"` // The constructed DAG
}

type RiskItem struct {
	Severity      string `json:"severity"` // CRITICAL, HIGH, MEDIUM
	Title         string `json:"title"`
	Description   string `json:"description"`
	Remediation   string `json:"remediation"`
	CausalLink    string `json:"causal_link_id"`
	STIGReference string `json:"stig_ref,omitempty"` // ID of the crossed STIG
}

// Ingest processing a Sonar snapshot and generates a Risk Report.
func Ingest(snapshotPath string, shodanKey string) (*RiskReport, error) {
	data, err := os.ReadFile(snapshotPath)
	if err != nil {
		return nil, err
	}

	var snap AuditSnapshot
	if err := json.Unmarshal(data, &snap); err != nil {
		return nil, fmt.Errorf("invalid snapshot format: %v", err)
	}

	// [KHEPRA INTELLIGENCE] Load STIG Library
	var stigLib []stigs.STIGItem
	if items, err := stigs.LoadLibrary("docs/STIG_to_NIST171_Mapping_Ultimate.xlsx"); err == nil {
		stigLib = items
		fmt.Printf("[KHEPRA] Applied Military Intelligence: %d STIG Controls loaded for analysis.\n", len(stigLib))
	} else {
		fmt.Printf("[KHEPRA] Warning: STIG Library not found. Running in civilian heuristics mode.\n")
	}

	// Initialize the Attestation DAG
	d := dag.NewMemory()

	// Create Root Node (The Host)
	hostNodeID := "asset:host:" + snap.Host.Hostname
	d.Add(&dag.Node{
		ID:     hostNodeID,
		Action: "Host Discovery",
		Symbol: "Asase Yaa (Earth)",
		Time:   snap.Timestamp.Format(time.RFC3339),
	}, nil)

	risks := []RiskItem{}

	// [SHODAN] External Exposure Verification
	if shodanKey != "" && snap.Host.PublicIP != "" {
		fmt.Printf("[KHEPRA] Verifying External Exposure for %s via Shodan...\n", snap.Host.PublicIP)
		client := shodan.New(shodanKey)
		hostInfo, err := client.GetHost(snap.Host.PublicIP)
		if err != nil {
			fmt.Printf("[KHEPRA] Shodan/Intel Warning: %v\n", err)
		} else {
			// Found open ports visible to the world
			if len(hostInfo.Ports) > 0 {
				nodeID := "risk:exposure:" + snap.Host.PublicIP
				d.Add(&dag.Node{
					ID:     nodeID,
					Action: "External Reconnaissance",
					Symbol: "Owo Foro Adobe (Snake/Prudence)",
					Time:   time.Now().Format(time.RFC3339),
				}, []string{hostNodeID})

				risks = append(risks, RiskItem{
					Severity:      "CRITICAL",
					Title:         "Publicly Exposed Services",
					Description:   fmt.Sprintf("Host %s is visible on public internet with open ports: %v. Detected via Shodan Intel.", snap.Host.PublicIP, hostInfo.Ports),
					Remediation:   "Immediate Firewall Review. Reference STIG AC-4 (Information Flow Enforcement).",
					CausalLink:    nodeID,
					STIGReference: "AC-000000", // Heuristic
				})
			}
		}
	}

	// Analyze Manifests (Supply Chain Risk)
	for _, m := range snap.Manifests {
		nodeID := "asset:file:" + m.Type + ":" + m.Checksum[:8]
		d.Add(&dag.Node{
			ID:     nodeID,
			Action: "Dependency Check",
			Symbol: "Funtunfunefu (Shared Stomach/Dependency)",
			Time:   time.Now().Format(time.RFC3339),
		}, []string{hostNodeID})

		if m.Type == "npm" {
			// Find relevant STIG (Heuristic Match)
			stigRef := "GEN-000000"
			stigTitle := "Unpinned Dependency"

			// Simple heuristic to find a Configuration Management STIG
			for _, s := range stigLib {
				if s.Family == "Configuration Management" && strings.Contains(s.Title, "software") {
					stigRef = s.ID
					stigTitle = s.Title
					break
				}
			}

			risks = append(risks, RiskItem{
				Severity:      "HIGH",
				Title:         "Unpinned NPM Dependency Tree",
				Description:   fmt.Sprintf("Manifest found at %s. Violation of CM protocol.", m.Path),
				Remediation:   "Evaluate against " + stigTitle,
				CausalLink:    nodeID,
				STIGReference: stigRef,
			})
		}
	}

	report := &RiskReport{
		Client:   snap.Host.Hostname,
		ScanID:   snap.ScanID,
		Risks:    risks,
		TrustMap: d,
	}

	return report, nil
}

// SaveReport writes the report to disk
func SaveReport(r *RiskReport, path string) error {
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}
