package audit

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/arsenal"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/dag"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/shodan"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/stigs"
	"github.com/EtherVerseCodeMate/giza-cyber-shield/pkg/zscan"
)

// RiskReport is the output generated by Khepra after analyzing a Sonar Snapshot.
type RiskReport struct {
	Client   string      `json:"client"`
	ScanID   string      `json:"scan_id"`
	Risks    []RiskItem  `json:"risks"`
	TrustMap *dag.Memory `json:"trust_map_snapshot"` // The constructed DAG
}

type RiskItem struct {
	Severity      string `json:"severity"` // CRITICAL, HIGH, MEDIUM
	Title         string `json:"title"`
	Description   string `json:"description"`
	Remediation   string `json:"remediation"`
	CausalLink    string `json:"causal_link_id"`
	STIGReference string `json:"stig_ref,omitempty"` // ID of the crossed STIG
}

// Ingest processing a Sonar snapshot and generates a Risk Report.
func Ingest(snapshotPath string, shodanKey string, gitleaksPath string, zscanPath string) (*RiskReport, error) {
	data, err := os.ReadFile(snapshotPath)
	if err != nil {
		return nil, err
	}

	var snap AuditSnapshot
	if err := json.Unmarshal(data, &snap); err != nil {
		return nil, fmt.Errorf("invalid snapshot format: %v", err)
	}

	// [KHEPRA INTELLIGENCE] Load STIG Library
	var stigLib []stigs.STIGItem
	if items, err := stigs.LoadLibrary("docs/STIG_to_NIST171_Mapping_Ultimate.xlsx"); err == nil {
		stigLib = items
		fmt.Printf("[KHEPRA] Applied Military Intelligence: %d STIG Controls loaded for analysis.\n", len(stigLib))
	} else {
		fmt.Printf("[KHEPRA] Warning: STIG Library not found. Running in civilian heuristics mode.\n")
	}

	// Initialize the Attestation DAG
	d := dag.NewMemory()

	// Create Root Node (The Host)
	hostNodeID := "asset:host:" + snap.Host.Hostname
	d.Add(&dag.Node{
		ID:     hostNodeID,
		Action: "Host Discovery",
		Symbol: "Asase Yaa (Earth)",
		Time:   snap.Timestamp.Format(time.RFC3339),
	}, nil)

	risks := []RiskItem{}

	// [SHODAN] External Exposure Verification
	if shodanKey != "" && snap.Host.PublicIP != "" {
		fmt.Printf("[KHEPRA] Verifying External Exposure for %s via Shodan...\n", snap.Host.PublicIP)
		client := shodan.New(shodanKey)
		hostInfo, err := client.GetHost(snap.Host.PublicIP)
		if err != nil {
			fmt.Printf("[KHEPRA] Shodan/Intel Warning: %v\n", err)
		} else {
			// Found open ports visible to the world
			if len(hostInfo.Ports) > 0 {
				nodeID := "risk:exposure:" + snap.Host.PublicIP
				d.Add(&dag.Node{
					ID:     nodeID,
					Action: "External Reconnaissance",
					Symbol: "Owo Foro Adobe (Snake/Prudence)",
					Time:   time.Now().Format(time.RFC3339),
				}, []string{hostNodeID})

				risks = append(risks, RiskItem{
					Severity:      "CRITICAL",
					Title:         "Publicly Exposed Services",
					Description:   fmt.Sprintf("Host %s is visible on public internet with open ports: %v. Detected via Shodan Intel.", snap.Host.PublicIP, hostInfo.Ports),
					Remediation:   "Immediate Firewall Review. Reference STIG AC-4 (Information Flow Enforcement).",
					CausalLink:    nodeID,
					STIGReference: "AC-000000", // Heuristic
				})
			}
		}
	} else {
		fmt.Println("[KHEPRA] External Reconnaissance (Shodan) disabled (No Key provided).")
	}

	// [SELF-HOSTED INTEL] ZScan Ingstion (IVRE/Natlas/ZGrab2)
	// Replaces Shodan Dependency
	if zscanPath != "" {
		fmt.Printf("[KHEPRA] Ingesting Self-Hosted Intelligence Artifact: %s\n", zscanPath)
		zresults, err := zscan.ParseZGrabFile(zscanPath)
		if err != nil {
			fmt.Printf("[WARN] Failed to parse ZScan artifact: %v\n", err)
		} else {
			fmt.Printf("[KHEPRA] ZScan loaded %d host records.\n", len(zresults))
			for _, res := range zresults {
				// Match against our host IP or just generic intel
				if res.IP == snap.Host.PublicIP || snap.Host.PublicIP == "" {
					// We treat any finding here as an exposure if it matches our IP
					nodeID := "risk:zscan:" + res.IP
					d.Add(&dag.Node{
						ID:     nodeID,
						Action: "ZGrab2 Verification",
						Symbol: "Hwe Mu Dua (Examination)",
						Time:   time.Now().Format(time.RFC3339),
					}, []string{hostNodeID})

					// TLS Analysis
					if res.Data.TLS.Status == "success" {
						params := res.Data.TLS.Result.HandshakeLog.ServerHello
						if strings.Contains(params.CipherSuite.Name, "RSA") || strings.Contains(params.CipherSuite.Name, "ECDH") {
							risks = append(risks, RiskItem{
								Severity:      "MEDIUM",
								Title:         "Quantum-Vulnerable Handshake (ZScan)",
								Description:   fmt.Sprintf("Detected %s using %s. Susceptible to Harvest-Now-Decrypt-Later.", params.Version.Name, params.CipherSuite.Name),
								Remediation:   "Plan Migration to Kyber-1024 or similar KEM.",
								CausalLink:    nodeID,
								STIGReference: "SC-13",
							})
						}
					}
				}
			}
		}
	}

	// [ARSENAL] Gitleaks / Secret Hunter
	if gitleaksPath != "" {
		fmt.Printf("[KHEPRA] Processing Interna Leakage via Gitleaks: %s\n", gitleaksPath)
		leaks, err := arsenal.ParseGitleaks(gitleaksPath)
		if err != nil {
			fmt.Printf("[WARN] Failed to parse Gitleaks report: %v\n", err)
		} else {
			for _, leak := range leaks {
				nodeID := fmt.Sprintf("risk:leak:%s:%d", leak.File, leak.StartLine)
				d.Add(&dag.Node{
					ID:     nodeID,
					Action: "Secret Leak Detected",
					Symbol: "Kuntinkantan (Hidden Wisdom/Secrets)", // Ironic usage
					Time:   time.Now().Format(time.RFC3339),
				}, []string{hostNodeID})

				risks = append(risks, RiskItem{
					Severity:      "CRITICAL",
					Title:         "Hardcoded Secret Detected",
					Description:   fmt.Sprintf("Secret leaked in %s (Line %d). Rule: %s. Author: %s", leak.File, leak.StartLine, leak.Description, leak.Author),
					Remediation:   "Rotate secret IMMEDIATELY. Revoke prior commits. Ref: STIG IA-5 (Authenticator Management).",
					CausalLink:    nodeID,
					STIGReference: "IA-000000",
				})
			}
			fmt.Printf("[KHEPRA] Identified %d confirmed secret leaks.\n", len(leaks))
		}
	}

	// Analyze Manifests (Supply Chain Risk)
	for _, m := range snap.Manifests {
		nodeID := "asset:file:" + m.Type + ":" + m.Checksum[:8]
		d.Add(&dag.Node{
			ID:     nodeID,
			Action: "Dependency Check",
			Symbol: "Funtunfunefu (Shared Stomach/Dependency)",
			Time:   time.Now().Format(time.RFC3339),
		}, []string{hostNodeID})

		if m.Type == "npm" {
			// Find relevant STIG (Heuristic Match)
			stigRef := "GEN-000000"
			stigTitle := "Unpinned Dependency"

			// Simple heuristic to find a Configuration Management STIG
			for _, s := range stigLib {
				if s.Family == "Configuration Management" && strings.Contains(s.Title, "software") {
					stigRef = s.ID
					stigTitle = s.Title
					break
				}
			}

			risks = append(risks, RiskItem{
				Severity:      "HIGH",
				Title:         "Unpinned NPM Dependency Tree",
				Description:   fmt.Sprintf("Manifest found at %s. Violation of CM protocol.", m.Path),
				Remediation:   "Evaluate against " + stigTitle,
				CausalLink:    nodeID,
				STIGReference: stigRef,
			})
		}
	}

	report := &RiskReport{
		Client:   snap.Host.Hostname,
		ScanID:   snap.ScanID,
		Risks:    risks,
		TrustMap: d,
	}

	return report, nil
}

// SaveReport writes the report to disk
func SaveReport(r *RiskReport, path string) error {
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}
