// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctxgyadqmjooxzuzbzkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0eGd5YWRxbWpvb3h6dXpiemtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjIzMDQsImV4cCI6MjA2MTk5ODMwNH0.v3Yl8jwaGTFYXBqpCqw3LLDJA4Sd2F9RaiUloFsrQuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);